import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e'
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(26, 26, 46, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayContent: {
    backgroundColor: '#16213e',
    padding: 30,
    borderRadius: 20,
    alignItems: 'center',
    minWidth: 280,
    borderWidth: 3,
    borderColor: '#0f3460',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  overlayTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  overlaySubtitle: {
    color: '#BDBDBD',
    fontSize: 16,
    marginBottom: 8,
  },
  gameOverTitle: {
    color: '#F44336',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  finalScore: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  finalDifficulty: {
    color: '#BDBDBD',
    fontSize: 14,
    marginBottom: 15,
  },
  newHighScore: {
    color: '#FFD700',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    textShadowColor: 'rgba(255, 215, 0, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  overlayButton: {
    backgroundColor: '#00C853',
    paddingHorizontal: 25,
    paddingVertical: 15,
    borderRadius: 25,
    marginVertical: 8,
    minWidth: 200,
    alignItems: 'center',
    shadowColor: '#00C853',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  overlayButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  overlayButtonSecondary: {
    backgroundColor: 'transparent',
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#666666',
    marginVertical: 5,
    minWidth: 180,
    alignItems: 'center',
  },
  overlayButtonSecondaryText: {
    color: '#CCCCCC',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(26, 26, 46, 0.95)',
  },
  modalContent: {
    backgroundColor: '#16213e',
    padding: 25,
    borderRadius: 20,
    minWidth: 300,
    borderWidth: 3,
    borderColor: '#0f3460',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  scoreItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 10,
  },
  topScoreItem: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 10,
    marginVertical: 2,
  },
  scoreRank: {
    color: '#BDBDBD',
    fontSize: 16,
    fontWeight: 'bold',
    width: 40,
  },
  scoreInfo: {
    flex: 1,
  },
  scoreValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scoreMeta: {
    color: '#9E9E9E',
    fontSize: 12,
  },
  crown: {
    fontSize: 16,
  },
  noScoresContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  noScoresText: {
    color: '#9E9E9E',
    fontSize: 16,
    marginBottom: 10,
  },
  noScoresSubtext: {
    color: '#757575',
    fontSize: 12,
  },
  closeButton: {
    backgroundColor: '#00C853',
    padding: 15,
    borderRadius: 15,
    marginTop: 20,
    alignItems: 'center',
    shadowColor: '#00C853',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  closeButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
});