import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gameContainer: {
    flex: 1,
    backgroundColor: '#1a1a2e'
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: '#16213e',
    borderBottomWidth: 2,
    borderBottomColor: '#0f3460',
  },
  scoreContainer: {
    alignItems: 'center',
  },
  scoreLabel: {
    color: '#BDBDBD',
    fontSize: 12,
    fontWeight: 'bold',
  },
  score: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    textShadowColor: 'rgba(255,255,255,0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  difficultyBadge: {
    backgroundColor: '#0f3460',
    paddingHorizontal: 15,
    paddingVertical: 6,
    borderRadius: 15,
    borderWidth: 1,
  },
  difficultyText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 14,
  },
  iconButton: {
    backgroundColor: '#0f3460',
    padding: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1a5f9e',
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  iconButtonText: {
    fontSize: 16,
  },
  gameArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
  },
  gameBorder: {
    borderWidth: 3,
    borderColor: '#0f3460',
    borderRadius: 12,
    backgroundColor: '#000000',
    shadowColor: '#00C853',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  gameEngine: {
    position: 'relative',
    backgroundColor: '#000000',
  },
  instructionOverlay: {
    position: 'absolute',
    top: 10,
    backgroundColor: 'rgba(76, 175, 80, 0.9)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  instructionOverlayText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  snakeSegment: {
    position: 'absolute',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  snakeEyeLeft: {
    position: 'absolute',
    width: 3,
    height: 3,
    backgroundColor: '#000',
    borderRadius: 2,
    top: 3,
    left: 3,
  },
  snakeEyeRight: {
    position: 'absolute',
    width: 3,
    height: 3,
    backgroundColor: '#000',
    borderRadius: 2,
    top: 3,
    right: 3,
  },
  food: {
    position: 'absolute',
    backgroundColor: '#F44336',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    elevation: 5,
  },
  foodInner: {
    width: '60%',
    height: '60%',
    backgroundColor: '#FF5252',
    borderRadius: 4,
  },
  foodSparkle: {
    position: 'absolute',
    width: 4,
    height: 4,
    backgroundColor: '#FFEB3B',
    borderRadius: 2,
    top: 2,
    right: 2,
  },
  controlsSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#16213e',
    borderTopWidth: 2,
    borderTopColor: '#0f3460',
  },
  controlsInfo: {
    flex: 1,
    alignItems: 'flex-end',
  },
  controlsTitle: {
    color: '#BDBDBD',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  controlsSubtitle: {
    color: '#9E9E9E',
    fontSize: 11,
    marginBottom: 5,
  },
  controlsStats: {
    color: '#4CAF50',
    fontSize: 12,
    fontWeight: 'bold',
  },
  joystickContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  joystickLabel: {
    color: '#9E9E9E',
    fontSize: 10,
    marginBottom: 8,
    fontWeight: 'bold',
  },
  joystickBase: {
    borderRadius: 50,
    backgroundColor: 'rgba(15, 52, 96, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#0f3460',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  joystickArea: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  joystickCenter: {
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.1)',
    position: 'absolute',
  },
  joystickThumb: {
    borderRadius: 25,
    backgroundColor: '#388E3C',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  directionIndicators: {
    position: 'absolute',
    top: '25%',
    left: '25%',
    right: '25%',
    bottom: '25%',
    justifyContent: 'space-between',
  },
  directionArrow: {
    color: 'rgba(255,255,255,0.2)',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  swipeArea: {
    position: 'absolute',
    top: -200,
    left: 0,
    right: 0,
    bottom: -200,
  },
});