import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  menuContainer: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'purple',
    paddingVertical: 40,
    paddingHorizontal: 20
  },
  menuBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  floatingWorm: {
    position: 'absolute',
    top: '20%',
    left: '20%',
  },
  floatingFood: {
    position: 'absolute',
    top: '30%',
    right: '20%',
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 10,
    borderRadius: 20,
  },
  food2: {
    top: '60%',
    left: '15%',
  },
  food3: {
    top: '70%',
    right: '30%',
  },
  wormEmoji: {
    fontSize: 40,
  },
  foodEmoji: {
    fontSize: 24,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 60,
  },
  logo: {
    fontSize: 80,
    marginBottom: 10,
    textShadowColor: 'rgba(0, 200, 83, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  title: {
    color: '#00C853',
    fontSize: 42,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
    textShadowColor: 'rgba(0, 200, 83, 0.3)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  subtitle: {
    color: '#64DD17',
    fontSize: 18,
    textAlign: 'center',
    opacity: 0.9,
    fontStyle: 'italic',
  },
  menuButtons: {
    width: '100%',
    alignItems: 'center',
    gap: 20,
  },
  primaryButton: {
    backgroundColor: '#00C853',
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderRadius: 30,
    minWidth: 250,
    alignItems: 'center',
    shadowColor: '#00C853',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  buttonGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 30,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    paddingHorizontal: 40,
    paddingVertical: 15,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#4CAF50',
    minWidth: 200,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#4CAF50',
    fontSize: 16,
    fontWeight: 'bold',
  },
  difficultySelector: {
    alignItems: 'center',
    marginTop: 10,
  },
  difficultyTitle: {
    color: '#E0E0E0',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  difficultyButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  diffButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 2,
    backgroundColor: '#16213e'
  },
  diffButtonActive: {
    backgroundColor: 'rgba(76, 175, 80, 0.15)',
  },
  diffButtonText: {
    color: '#E0E0E0',
    fontSize: 14,
    fontWeight: '600',
  },
  instructions: {
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 20,
    borderRadius: 15,
    width: '90%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  instructionTitle: {
    color: '#4CAF50',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  instructionText: {
    color: '#BDBDBD',
    fontSize: 14,
    marginBottom: 8,
    textAlign: 'center',
  },
});
